api:
  key: sCYmf0y9

batch:
  processing:
    enabled: true
    
message:
  batch:
    size: 10
  polling:
    interval: 10
    

  
server:
  port: 8082
  tomcat:
    threads:
      min-spare: 10
      max: 200
    accept-count: 200
    max-connections: 5000
    connection-timeout: 20000
  
  
auth:
  bearer-token: sCYmf0y9

spring:
  application:
    name: DB2_Pick_App
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    password: Sarthak@51
    url: jdbc:db2://localhost:50012/SAMPLE
    username: db2inst2
    hikari:
      connection-test-query : SELECT 1 FROM SYSIBM.SYSDUMMY1
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 5000
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: DB2ConnectionPool
      registerMbeans: true
  
  
  
  jpa:
    database-platform: org.hibernate.dialect.DB2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        hibernate:
          format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: true
    
    
thread:
  pool:
    core:
      size: 5
    max:
      size: 10
    queue:
      capacity: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator  # This is default
      
      
      
logging:
  level:
    org.apache.tomcat.util.threads: DEBUG
    org.apache.catalina.core: DEBUG
    org.apache.coyote.http11.Http11NioProtocol: DEBUG
    root: INFO
    org.springframework: INFO